model:
  model_name: "facebook/bart-large-cnn"
  model_path: "models/summarization_model_fine_tuned"

training:
  learning_rate: 0.00005
  batch_size: 3
  epochs: 10

logging:
  log_dir: "data/logs/"

lora:
  lora_dropout: 0.1
  r: 12
  lora_alpha: 16
